language: java
jdk:
- oraclejdk8
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
before_install:
- export TZ=Pacific/Noumea
install: mvn clean install checksum:files -DskipTests=true -Dmaven.javadoc.skip=true
  -B -V
script:
- mvn versioneye:update test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: JtB01gp/F7yV9NP4k1+SBboESUxeTDFUaUKC201cAonoVQKzH0Uyw4FXNCFTdOeUBeqfLB1jymJJUOMPBQuKHK420bk48TeggLdvl2lNfeppCqWijsINUXa+NmU0KuueOo8dKSyyyy0M1RcwX6vj6mhBbdi0S5SBzocLXLRYdrA+19ZynwJysSl977g1mNtd87vkhLb2PvOM01tGOvRkrEL5wkt9iOdIPho6BSY/ufw/eCfuOycNOb1Lqq4p3mSGQ8AkwR8X1Hx+xmfVRbKHi9fyekPnUCmuuRUMs2cdRVrTwFKMnEVfrG0Lyr7Rbs31l50irm50EjrNE5gb7M9noWV3BTvfQB8aYzev6jhM3lBeKDzVG5USI4EQ6fELcsJM2c1jWaI6APgCy+LXKVFuZGxsYHO6kWgaep64PuHsr92aIcpZqprkFk3LLhvj+D8V5MUpZQwqz3Kme7VvpGh85vptDVTp7x9jkHNRjGJUFR6KH3v8ZrQuzaTqjdbTNV1AhSF5+ODoK58OJkXMTvLdzeXBvtLJydzWH22BuKxenoTQ4MmXrrPkYhVePxzEnKBth5xke9hwc9StME0EvqYIPSpcP306fE1LfEtdK9pSNKn4OSnvklOZyqBgpi2qKpc8rUrfIZ8x/bW9aAdyJ6jrYzGMIN95XNMtXWeWtaETdxk=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/ads
notifications:
  slack:
    secure: uu0L9MZAhvPn5if2Pslg2tnHfpqJqO3swXn3wbbCrE2ytOoVoFGu4Abi4HvIA7FuKMLRyuM3eyugSE7sPBpNbFZegI141Tw2FWiqH2ba3VmtUgI5s5+8AUwJjU1NpjiVmW2zOApGen+EqQzo0CsDx/OBDTCjow00giDDHM7kRb+kR9R4e6tYVV9MiP+3Vo+rf92d8XtE5Q5Rj0HNrEDQe/YrhSDjRKrB3yNpcFkITBZeECgNvJ+VbGrr8IyfIbL6/4V+W712dSz1g68RHfXwxWKjp8r8J5DisNVqCqaMdnJgmVnSs2igerAgUsfDcWxSXfOox+IOqtWLsAKpm/yiKUPGBPbBl2HhpoZRCtHqqIVptJI+y3reEdLtmRRiYYbOA793+fzVxKkXqdx/Fzb2+pvHHUVlswa7ZrUCrdrb6cZAYmbRML4hGp3sPyXQkC6mGsaB4yfP/AR87mL9pGcwPXU1BA4awpJc5PYlO9uDXvsPS+4IacBKNvPchV4Qmj6j1e8c3DLAD3dGv13acnNxEhEWJ4jz2kkc/Zb32ZIQIXa03cc3ALA4IHLiJAyw96EAkvzhXR6kHhIXGzLegW5e5/Exktt3Bkk3HAGw3LuDRP6z0nVR33LGi4QLuVvWSI/x3Fsxu0nBLxUHuukCvds9tJ75jeIJZUhqzWRPvjh99s0=
env:
  global:
  - secure: I2b9FnYSWwDW2Tynf/62BkEROvEwMgALvhnkChDLllBnUxGbRQWQvF9u1qVZIvxeZnyPKzO4Ku6ufTa7C75y4T9otR+PAjnObyEe9jw/nyO59jzpGefynHqkO8TcHlMOy5reso7xye+vfRnygFjeuif/pTydDiOphWXOvHl6bfoF7fIC20G+hs5jguRK0R9hscGLxzwV7cHkboynTMZWpgR5QFL37jqG3S1YbsD/XHqWd4YMmR7tnaeJEKJmQ907IJ9dZMrwNY++423H9E6PjJNPNqjyEgMxatiPYhEmKh8xsyQo1zsb2yiNug2zCT43PSl+9HlB7ai0w+2JXnzJJ+7uLJoKsSjaVDw/ymG+ozJn0A7hwQEmxDTMNgE2umdWl58SBBTbW4woprBeSiupeTY6SGpX60d3V265gZZeEBc2RQ+iY2w1x8Z0dlEUEJyf016sEFrQjXIx5CMXlbV5jjcI1uZrVUcmU6GVRWKU6oQexRI5KwXa2x3Chf/nfczcdK9iaVFQah7M+/LykN2hN+pUcZO9YT+O4eAx9xCEf2+BJB/G0JRiqnhy/rIz2NMRwcXT/KIeIc7XO/e6yiIPo9cC4BOsuo4+LSiGorS3aUGuYOC79LxnrbETEG+2TX3LqAk7tZsJ3Yp1+B2cnDfhjrC0Vh0V/5nO3FhrDsyBFcM=
  - secure: GIcW/7PTprHaV9Ye3eARijQNVg2f85LWYZ2M/C5xfWxnxsJRU86s+4gGgvi5nr7QVnWeOLxqd/pXHB2DfPrFiHrYSKnMUzzPjZOP2AkwM5GcVLdOSDEFBPTK0YD5s6clvwuYJXdHui35xDeRIAUjL5fc7zV8+BqL0ojOsXPcVfY3KEl9XbfP6qU7mjIz2yh7nL2Ix9ppOs71ubiMbPYDyT0p2jkodDV+QNGbrvVos7ZES8w3h9iDOP//iXSXGFxaA6DDVgYJpDEOfvl3U0s72YrQ5kyt+hA8OIRA31kKuya6CQr4A6wEFRZm9Xw/8yrV9MUldrmYv+W79f9P2JWYcTr5Q0FxYM5f02EqYKV876zqETItO5queoUUENPSmYSAiCL+5+vzI8uLj1OFhd1jGzEgVIE41Hh7/N4Dkt0z0FVVnYjaVhfcVRBW3cmRpLiiu6QjWQzyyjKTc9bxn9Yd+rtNu3kpzNG71g+59Jo2HMFQw7+nZXANLDuE/0HlNHj2vKVzVQ+QF0iSEGW/8SDKgscTfa6TC2TRLnMsYFEIB0qxyLpW8bYvY5MbHjllR6bmgOfi+Z0zGKibgET6VqvROhwIc1OE1ODRUuv0o1OF7b+iBAUHEx4lr62qlkOCguneYZjyw9qjS4qFDAyLI92fCkwBzt5y3XYgPksJBjm/3QY=
