language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- export TZ=Pacific/Noumea
- git clone -b travis `git config --get remote.origin.url` target/travis
install: mvn clean install checksum:files -DskipTests=true -Dmaven.javadoc.skip=true
  -B -V
script:
- mvn versioneye:update test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.war)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.war.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.war.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
env:
  global:
  - secure: I2b9FnYSWwDW2Tynf/62BkEROvEwMgALvhnkChDLllBnUxGbRQWQvF9u1qVZIvxeZnyPKzO4Ku6ufTa7C75y4T9otR+PAjnObyEe9jw/nyO59jzpGefynHqkO8TcHlMOy5reso7xye+vfRnygFjeuif/pTydDiOphWXOvHl6bfoF7fIC20G+hs5jguRK0R9hscGLxzwV7cHkboynTMZWpgR5QFL37jqG3S1YbsD/XHqWd4YMmR7tnaeJEKJmQ907IJ9dZMrwNY++423H9E6PjJNPNqjyEgMxatiPYhEmKh8xsyQo1zsb2yiNug2zCT43PSl+9HlB7ai0w+2JXnzJJ+7uLJoKsSjaVDw/ymG+ozJn0A7hwQEmxDTMNgE2umdWl58SBBTbW4woprBeSiupeTY6SGpX60d3V265gZZeEBc2RQ+iY2w1x8Z0dlEUEJyf016sEFrQjXIx5CMXlbV5jjcI1uZrVUcmU6GVRWKU6oQexRI5KwXa2x3Chf/nfczcdK9iaVFQah7M+/LykN2hN+pUcZO9YT+O4eAx9xCEf2+BJB/G0JRiqnhy/rIz2NMRwcXT/KIeIc7XO/e6yiIPo9cC4BOsuo4+LSiGorS3aUGuYOC79LxnrbETEG+2TX3LqAk7tZsJ3Yp1+B2cnDfhjrC0Vh0V/5nO3FhrDsyBFcM=
  - secure: GIcW/7PTprHaV9Ye3eARijQNVg2f85LWYZ2M/C5xfWxnxsJRU86s+4gGgvi5nr7QVnWeOLxqd/pXHB2DfPrFiHrYSKnMUzzPjZOP2AkwM5GcVLdOSDEFBPTK0YD5s6clvwuYJXdHui35xDeRIAUjL5fc7zV8+BqL0ojOsXPcVfY3KEl9XbfP6qU7mjIz2yh7nL2Ix9ppOs71ubiMbPYDyT0p2jkodDV+QNGbrvVos7ZES8w3h9iDOP//iXSXGFxaA6DDVgYJpDEOfvl3U0s72YrQ5kyt+hA8OIRA31kKuya6CQr4A6wEFRZm9Xw/8yrV9MUldrmYv+W79f9P2JWYcTr5Q0FxYM5f02EqYKV876zqETItO5queoUUENPSmYSAiCL+5+vzI8uLj1OFhd1jGzEgVIE41Hh7/N4Dkt0z0FVVnYjaVhfcVRBW3cmRpLiiu6QjWQzyyjKTc9bxn9Yd+rtNu3kpzNG71g+59Jo2HMFQw7+nZXANLDuE/0HlNHj2vKVzVQ+QF0iSEGW/8SDKgscTfa6TC2TRLnMsYFEIB0qxyLpW8bYvY5MbHjllR6bmgOfi+Z0zGKibgET6VqvROhwIc1OE1ODRUuv0o1OF7b+iBAUHEx4lr62qlkOCguneYZjyw9qjS4qFDAyLI92fCkwBzt5y3XYgPksJBjm/3QY=
  - secure: mpM0q8NWumXmu5CDMVGSge8PNAhrNmHgrzohsvAPJ7yYN0CPaqXqIFke7XAOuouXARd5Oa1d/h+rDqv+tEp2yWWreOf09d3m1wf96Rg+9lJ8qRp5mNutaZyVc2ys2NOqUjrf8L1l5LQMnV7zrWdkYh/3pzHUolMbt3l5W5HLUqfwTilpoyHRzQ9oW+onpmnCHsaDnaw8ljaC7xbH3mQy8gN/05Or661dULgOTJzEyjyD0HhaOyQZqIRdAPqbhYdu6MGoPbYLjmwZG1JzG69cPeSwH28FDehfKhBpSY++5xk5t1wNygnxBWIUnZLkDDNky6DYPTQL1XbVtjbTbNiknzgbDjiqtlHVd74X4Ajsbxqfg/8ragdUL1twN7wewKUtUSHSDNmXByv43XgxEMNPPwtB/4nP2XKFDi2GZjDkLTfdXOdSXoESZUiCDwtf9jORMOpYTRlRQiI9sT6Yv9zfA/6aFBBQuB8WUI1cgnAFY44+4vZKVizbFM2Q8jDULkRK0tR0wS8goZiCUHwhICCgtzSTEggwnMb8UeIna+Eps306GmCoMz04vT6WmYsa38NHUB9H1MmpaxaBjJaVmGkFRHNmdx2Kf9tl58Kb6xPe/bdfNdn/JNChGU+YuHNrtz7OqkxwTzPD1Gl3gxnRLy3Grdz6bbN0RmYCoCWg9fMJLog=
deploy:
  provider: releases
  api_key:
    secure: JtB01gp/F7yV9NP4k1+SBboESUxeTDFUaUKC201cAonoVQKzH0Uyw4FXNCFTdOeUBeqfLB1jymJJUOMPBQuKHK420bk48TeggLdvl2lNfeppCqWijsINUXa+NmU0KuueOo8dKSyyyy0M1RcwX6vj6mhBbdi0S5SBzocLXLRYdrA+19ZynwJysSl977g1mNtd87vkhLb2PvOM01tGOvRkrEL5wkt9iOdIPho6BSY/ufw/eCfuOycNOb1Lqq4p3mSGQ8AkwR8X1Hx+xmfVRbKHi9fyekPnUCmuuRUMs2cdRVrTwFKMnEVfrG0Lyr7Rbs31l50irm50EjrNE5gb7M9noWV3BTvfQB8aYzev6jhM3lBeKDzVG5USI4EQ6fELcsJM2c1jWaI6APgCy+LXKVFuZGxsYHO6kWgaep64PuHsr92aIcpZqprkFk3LLhvj+D8V5MUpZQwqz3Kme7VvpGh85vptDVTp7x9jkHNRjGJUFR6KH3v8ZrQuzaTqjdbTNV1AhSF5+ODoK58OJkXMTvLdzeXBvtLJydzWH22BuKxenoTQ4MmXrrPkYhVePxzEnKBth5xke9hwc9StME0EvqYIPSpcP306fE1LfEtdK9pSNKn4OSnvklOZyqBgpi2qKpc8rUrfIZ8x/bW9aAdyJ6jrYzGMIN95XNMtXWeWtaETdxk=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/ads
notifications:
  slack:
    secure: FJWjnBl7o76+pJ6foaQBtEAmJWlagsTmXMDe5cgVPoqkLl19UZBLBeOfjDLoxn4hVEnj61iVoFZTpLG4Tnp+vSr6/KysqR+BNmDUaejeVdak0/+ThC7jSwJNI5J99cWZfoFHDHlalcNHvqVjjPuOnJo/EgCs9Tq4m2SP0iQUJUJ0RIVbNtIrcvqPAE2RCZpnIAkI4ndm6FpNkSCMgEhZUsTFqfj8QY2sCBfPodQj+HncW9DewRAQ5efqwtJ0bx1IQkRVxwjBbC44CqZ7/8ZatHADoV7/Ws3ewXCEkda5/9Ic6G0vQU/e1C9Mc+cnokt4KjDgqLrRdAnsYb4E5oFHiyYvnEbFO+wqRfoDfToPVIrVZ2XaBNlv3bEAg28oujTE/9+4pHYQaOPkf7ufyNO4UMYO643s7XHzsQ+2nWp7/b/gT6iG7D4kPdjFAhInKHpJ7UrFRaDGN0vmx0YLIhCrfYNEyJMQx8HQc67DmgsvYG1Olr9nuI8sPQwh7U33G/Ehy4g2UB3Nav9iC1MwMrR9oRbub/05MVVA9GlNwKWFSwys/hows7BpOLQV2L5k9s6e9vUfcaW2jWvgjXBxLUazzP/o6tJ8ichFkIj2hku8mP/a77pfuUWmvtZNcU/e9Lkov+/JJPknQ5I8PRPvThHvNwIyMUcg4k4Zfye2bkqQH48=
